# -*- coding: utf-8 -*-
"""music_studio (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaSShVhRgTP84rT4n1mMgni6GuBUOCR6

# 🎵 Music Studio — Download · Identify · Complete
**Partie 1** — Téléchargement (Instagram / YouTube)  
**Partie 2** — Identification du titre (AudD.io) + Genre (HuggingFace)  
**Partie 3** — Génération des parties manquantes (→ 2min30)  
**Partie 4** — Interface graphique unifiée

---
## 📦 PARTIE 1 — Téléchargement
"""

# Cellule 1.1 — Installation Partie 1
# yt-dlp est volontairement NON épinglé : il doit rester à jour pour suivre les
# changements d'Instagram/YouTube (une version figée casse l'extraction avec le temps).
import sys
!{sys.executable} -m pip install -U yt-dlp --quiet
print('✅ yt-dlp installé')

# Cellule 1.2 — Imports & fonctions Partie 1
import yt_dlp, os, glob

def p1_download(url: str, fmt: str = 'mp3', cookies_path: str = '') -> dict:
    # Validation d'URL : limite aux domaines Instagram / YouTube en http(s)
    # (évite qu'une URL arbitraire — file://, hôte interne… — soit passée à yt-dlp).
    from urllib.parse import urlparse
    parsed = urlparse(url)
    allowed = ('instagram.com', 'youtube.com', 'youtu.be')
    host = (parsed.hostname or '').lower()
    if parsed.scheme not in ('http', 'https') or not any(host == d or host.endswith('.' + d) for d in allowed):
        return {'success': False, 'path': '', 'title': '',
                'error': 'URL non autorisée (Instagram / YouTube en http(s) uniquement).'}
    out_dir = './downloads'
    os.makedirs(out_dir, exist_ok=True)
    # Garde-fous communs : borne la taille (évite de saturer le disque de la VM
    # avec une longue vidéo) et restreint les noms de fichiers (titres exotiques).
    MAX_FILESIZE = 200 * 1024 * 1024  # 200 Mo
    # `max_filesize` ne s'applique que si le format ANNONCE sa taille ; beaucoup de
    # flux (HLS, certains Reels) ne la déclarent pas. Ce hook borne réellement le
    # disque en interrompant dès que la taille (déclarée OU déjà téléchargée) dépasse.
    def _abort_if_too_big(d):
        if d.get('status') != 'downloading':
            return
        total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
        if total > MAX_FILESIZE or d.get('downloaded_bytes', 0) > MAX_FILESIZE:
            raise Exception('Fichier trop volumineux (> 200 Mo) — téléchargement interrompu.')
    if fmt == 'mp4':
        ydl_opts = {
            'format': 'bestvideo+bestaudio/best',
            'outtmpl': f'{out_dir}/%(title)s.%(ext)s',
            'merge_output_format': 'mp4',
            'restrictfilenames': True,
            'max_filesize': MAX_FILESIZE,
            'progress_hooks': [_abort_if_too_big],
            'noplaylist': True,
            'quiet': True, 'no_warnings': True,
        }
    else:
        ydl_opts = {
            'format': 'bestaudio/best',
            'outtmpl': f'{out_dir}/%(title)s.%(ext)s',
            'restrictfilenames': True,
            'max_filesize': MAX_FILESIZE,
            'progress_hooks': [_abort_if_too_big],
            'noplaylist': True,
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': fmt,
                'preferredquality': '320' if fmt == 'mp3' else '0',
            }],
            'quiet': True, 'no_warnings': True,
        }
    # isfile : refuse répertoires / chemins spéciaux ; .txt : restreint à un vrai
    # fichier cookies (réduit la lecture de fichiers locaux arbitraires).
    if cookies_path and os.path.isfile(cookies_path) and cookies_path.lower().endswith('.txt'):
        ydl_opts['cookiefile'] = cookies_path
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get('title', 'audio')
            base = ydl.prepare_filename(info)
        # Après extraction audio l'extension devient `fmt` (mp3/wav) ; pour le
        # mp4 c'est déjà la bonne. On cible le fichier exact de CE téléchargement
        # au lieu du plus récent du dossier (qui pouvait être un ancien fichier).
        expected = os.path.splitext(base)[0] + f'.{fmt}'
        if os.path.exists(expected):
            return {'success': True, 'path': expected, 'title': title, 'error': ''}
        # Repli : fichier le plus récent du bon format.
        files_found = sorted(glob.glob(f'{out_dir}/*.{fmt}'), key=os.path.getmtime, reverse=True)
        if files_found:
            return {'success': True, 'path': files_found[0], 'title': title, 'error': ''}
        return {'success': False, 'path': '', 'title': '', 'error': 'Fichier introuvable après téléchargement'}
    except Exception as e:
        return {'success': False, 'path': '', 'title': '', 'error': str(e)}

def p1_get_audio_files(audio_only: bool = True):
    # Les dropdowns d'identification (P2) et de complétion (P3) ne doivent lister
    # que des fichiers décodables par torchaudio : on exclut les .mp4 (conteneur
    # vidéo non décodable tel quel) par défaut.
    patterns = ['*.mp3', '*.wav'] if audio_only else ['*.mp3', '*.wav', '*.mp4']
    f = []
    for pat in patterns:
        f += glob.glob(f'./downloads/{pat}')
    return sorted(os.path.basename(x) for x in f)

print('✅ Partie 1 prête')

"""---
## 🔍 PARTIE 2 — Identification (AudD.io + HuggingFace)
"""

# Cellule 2.1 — Installation Partie 2
# Versions épinglées (reproductibilité + réduit le risque supply-chain).
# requests aligné sur 2.32.4 = version attendue par google-colab/google-adk (supprime les warnings de conflit).
# torch/torchaudio alignés sur 2.11.0 = version attendue par le torchvision préinstallé de Colab.
# Évite « RuntimeError: operator torchvision::nms does not exist » sans réinstaller torchvision.
!pip install "transformers==4.44.2" "requests==2.32.4" "torch==2.11.0" "torchaudio==2.11.0" --quiet  # versions épinglées et alignées sur le runtime Colab
print('✅ Dépendances Partie 2 installées')

# Cellule 2.2 — Imports & fonctions Partie 2
import os
import torch
import torchaudio
import numpy as np
import requests
from transformers import pipeline

# ─── AudD.io — Reconnaissance du titre exact ───
def p2_identify_title(audio_path: str, audd_key: str) -> dict:
    if not audd_key:
        return {'success': False, 'title': '', 'artist': '', 'album': '', 'error': 'Pas de clé AudD fournie'}
    try:
        with open(audio_path, 'rb') as f:
            data = {'api_token': audd_key, 'return': 'apple_music,spotify'}
            # timeout = (connexion, lecture) : l'upload d'un WAV un peu lourd
            # dépasse facilement 15 s -> sinon échec systématique par timeout.
            result = requests.post('https://api.audd.io/', data=data, files={'file': f}, timeout=(10, 120)).json()
        if result.get('status') == 'success' and result.get('result'):
            r = result['result']
            spotify = r.get('spotify') or {}
            apple = r.get('apple_music') or {}
            return {
                'success': True,
                'title': r.get('title') or '?',
                'artist': r.get('artist') or '?',
                'album': r.get('album') or '?',
                'release_date': r.get('release_date') or '?',
                'spotify_url': spotify.get('external_urls', {}).get('spotify', ''),
                'apple_url': apple.get('url', ''),
                'error': ''
            }
        return {'success': False, 'title': '', 'artist': '', 'album': '',
                'error': result.get('error', {}).get('error_message', 'Titre non trouvé')}
    except Exception as e:
        return {'success': False, 'title': '', 'artist': '', 'album': '', 'error': str(e)}


# ─── HuggingFace — Détection du genre (2 modèles) ───
P2_MODELS = [
    {
        'id': 'laion/clap-htsat-unfused',
        'name': 'CLAP (LAION)',
        'type': 'zero-shot-audio-classification',
        'description': 'Modèle contrastif audio-texte, très bon pour la classification de genre',
        'labels': [
            'pop music', 'hip hop', 'electronic music', 'rock music', 'jazz',
            'classical music', 'r&b soul', 'reggaeton', 'latin music', 'house music',
            'techno', 'trap music', 'lo-fi music', 'ambient music', 'funk',
            'metal', 'indie music', 'dance music', 'afrobeats', 'drill music'
        ]
    },
    {
        'id': 'MIT/ast-finetuned-audioset-10-10-0.4593',
        'name': 'AST (MIT AudioSet)',
        'type': 'audio-classification',
        'description': 'Audio Spectrogram Transformer (AudioSet, 527 classes) — détecte les évènements sonores et instruments, pas uniquement le genre'
    }
]

# Cache de décodage : torchaudio.load est coûteux ; on évite de re-décoder le
# même fichier entre l'identification (Partie 2) et la complétion (Partie 3).
# LRU borné aux 2 derniers fichiers : alterner entre deux pistes ne force plus
# un re-décodage à chaque bascule (mémoire restant bornée).
from collections import OrderedDict
_AUDIO_RAW_CACHE = OrderedDict()
_AUDIO_RAW_MAX = 2
def _load_raw(path: str):
    st = os.stat(path)
    sig = (st.st_mtime, st.st_size)      # mtime + taille : invalide le cache même si un
    cached = _AUDIO_RAW_CACHE.get(path)  # fichier est remplacé en gardant le même mtime
    if cached and cached[0] == sig:
        _AUDIO_RAW_CACHE.move_to_end(path)
        return cached[1], cached[2]
    waveform, sr = torchaudio.load(path)
    _AUDIO_RAW_CACHE[path] = (sig, waveform, sr)
    _AUDIO_RAW_CACHE.move_to_end(path)
    while len(_AUDIO_RAW_CACHE) > _AUDIO_RAW_MAX:
        _AUDIO_RAW_CACHE.popitem(last=False)
    return waveform, sr

def _to_mono(path: str, target_sr: int, max_seconds=None) -> np.ndarray:
    # Chargement mono + rééchantillonnage, partagé entre P2 et P3.
    waveform, sr = _load_raw(path)
    if max_seconds is not None:
        waveform = waveform[:, :int(max_seconds * sr)]   # tronquer AVANT le resample
    if waveform.shape[0] > 1:                            # mono AVANT le resample : ~2x moins
        waveform = waveform.mean(dim=0, keepdim=True)    # d'échantillons à rééchantillonner
    if sr != target_sr:
        waveform = torchaudio.functional.resample(waveform, sr, target_sr)
    return waveform.squeeze().numpy().copy()             # copie : ne pas exposer le tenseur du cache

_P2_PIPES = {}
def p2_get_pipe(model_info: dict):
    # Chargé une seule fois puis réutilisé : évite de re-télécharger/recharger
    # le modèle à chaque identification (gros gain de temps).
    key = model_info['id']
    if key not in _P2_PIPES:
        dev = 0 if torch.cuda.is_available() else -1
        _P2_PIPES[key] = pipeline(model_info['type'], model=key, device=dev)
    return _P2_PIPES[key]

def p2_run_model(model_info: dict, audio_path: str) -> dict:
    try:
        clf = p2_get_pipe(model_info)
        # Chaque modèle attend SON sample rate (CLAP=48k, AST=16k). Décoder à la
        # fréquence du feature extractor évite d'interpréter le signal à la mauvaise
        # vitesse -> genres faussés. Le waveform brut reste mis en cache (_load_raw),
        # seul le rééchantillonnage diffère d'un modèle à l'autre.
        sr = int(getattr(getattr(clf, 'feature_extractor', None), 'sampling_rate', 16000) or 16000)
        audio_np = _to_mono(audio_path, sr, max_seconds=30)
        if model_info['type'] == 'zero-shot-audio-classification':
            # audio déjà décodé au SR du modèle ; le kwarg sampling_rate n'est pas
            # accepté par le pipeline zero-shot selon la version de transformers.
            results = clf(audio_np, candidate_labels=model_info['labels'])
        else:
            results = clf(audio_np, sampling_rate=sr, top_k=5)
        return {
            'success': True,
            'model_name': model_info['name'],
            'description': model_info['description'],
            'top_results': [{'label': r['label'], 'score': r['score']} for r in results[:5]],
            'error': ''
        }
    except Exception as e:
        return {
            'success': False,
            'model_name': model_info['name'],
            'description': model_info.get('description', ''),
            'top_results': [],
            'error': str(e)
        }

def p2_identify_all(audio_path: str, audd_key: str = '', progress_cb=None, models=None) -> dict:
    # `models` : sous-ensemble de P2_MODELS choisi dans l'UI (évite de faire tourner
    # les deux modèles si l'utilisateur n'en veut qu'un — gros gain sur CPU).
    models = models if models is not None else P2_MODELS
    total = 1 + len(models)
    if progress_cb: progress_cb(0, total, '⏳ Identification du titre via AudD.io...')
    title_result = p2_identify_title(audio_path, audd_key)
    if progress_cb: progress_cb(1, total, '✅ Titre traité — analyse des genres...')
    genre_results = []
    for i, model_info in enumerate(models):
        if progress_cb:
            progress_cb(1 + i, total, f'⏳ Modèle {i+1}/{len(models)} : {model_info["name"]}...')
        genre_results.append(p2_run_model(model_info, audio_path))   # décodé au bon SR par modèle
    if progress_cb: progress_cb(total, total, '✅ Analyse complète !')
    return {'title': title_result, 'genres': genre_results}

print('✅ Partie 2 prête —', len(P2_MODELS), 'modèles genre + AudD.io pour le titre')

"""---
## 🎼 PARTIE 3 — Complétion musicale (→ 2min30)
"""

# Cellule 3.1 — Installation Partie 3
# Versions épinglées (reproductibilité + réduit le risque supply-chain).
# torchaudio aligné sur 2.11.0 = même version que torch (cohérence avec la Partie 2).
# scipy aligné sur 1.14.1 = satisfait access (>=1.14.1) et tsfresh (>=1.14.0) préinstallés sur Colab (supprime les conflits du resolver pip).
!pip install "transformers==4.44.2" "accelerate==0.34.2" "scipy==1.14.1" "torchaudio==2.11.0" --quiet
print('✅ Dépendances Partie 3 installées')

# Cellule 3.2 — Imports & chargement modèle (small par défaut)
import os
import torch
import torchaudio
import scipy.io.wavfile
import numpy as np
from transformers import AutoProcessor, MusicgenForConditionalGeneration

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'🖥️ Device : {device}')
if device == 'cpu':
    print('⚠️ Pas de GPU ! Va dans Exécution → Modifier le type d\'exécution → GPU T4')

P3_MODEL_NAME = 'facebook/musicgen-small'
p3_processor = None
p3_model = None

def p3_load_model():
    global p3_processor, p3_model
    if p3_model is not None:
        return True
    try:
        print(f'⏳ Chargement {P3_MODEL_NAME}...')
        p3_processor = AutoProcessor.from_pretrained(P3_MODEL_NAME)
        dtype = torch.float16 if device == 'cuda' else torch.float32   # fp16 sur GPU : ~2x + moins de VRAM
        p3_model = MusicgenForConditionalGeneration.from_pretrained(
            P3_MODEL_NAME, torch_dtype=dtype).to(device)
        print(f'✅ Modèle chargé sur {device.upper()}')
        return True
    except Exception as e:
        print(f'❌ Erreur chargement modèle : {e}')
        return False

print('✅ Partie 3 prête (modèle chargé à la première génération)')

# Cellule 3.3 — Fonctions de génération et assemblage
TARGET_DURATION = 150  # 2min30 en secondes
CHUNK_SIZE = 20        # secondes par chunk (plus grand = moins d'appels generate)

def p3_load_audio_mono(path: str, target_sr: int) -> np.ndarray:
    return _to_mono(path, target_sr)

def p3_save_tmp(audio_np: np.ndarray, sr: int, path: str):
    if audio_np.size == 0:                       # garde : np.max([]) lèverait ValueError
        scipy.io.wavfile.write(path, sr, np.zeros(1, dtype=np.int16))
        return
    norm = (audio_np / (np.max(np.abs(audio_np)) + 1e-9) * 32767).astype(np.int16)
    scipy.io.wavfile.write(path, sr, norm)

def _match_peak(arr: np.ndarray, ref_peak: float) -> np.ndarray:
    # Aligne le pic d'un segment généré sur celui de l'extrait réel : sans ça, une
    # intro/outro plus forte écrase le volume de l'extrait lors de la normalisation
    # finale (qui normalise sur le pic global du mix).
    if arr.size == 0 or ref_peak <= 0:
        return arr
    peak = float(np.max(np.abs(arr)))
    return arr * (ref_peak / peak) if peak > 0 else arr

def p3_crossfade_join(parts, sr, fade=0.05):
    # Fond enchaîné court aux jonctions pour lisser clics et sauts de volume.
    parts = [p for p in parts if len(p) > 0]
    if not parts:
        return np.array([])
    n = max(1, int(sr * fade))
    out = parts[0].astype(np.float32)
    for nxt in parts[1:]:
        nxt = nxt.astype(np.float32)
        m = min(n, len(out), len(nxt))
        if m > 0:
            ramp = np.linspace(0.0, 1.0, m, dtype=np.float32)
            out[-m:] = out[-m:] * (1 - ramp) + nxt[:m] * ramp
            out = np.concatenate([out, nxt[m:]])
        else:
            out = np.concatenate([out, nxt])
    return out

def p3_generate_chunk(context_np: np.ndarray, sr: int, chunk_dur: int, prompt: str = 'music') -> np.ndarray:
    # MusicGen (small) est un modèle texte→musique : on lui fournit un prompt
    # texte ET l'audio de contexte (continuation audio-promptée). `padding=True`
    # est requis quand audio + texte sont combinés.
    max_tokens = int(chunk_dur * p3_model.config.audio_encoder.frame_rate)
    context = context_np[-(sr * 10):]
    inputs = p3_processor(
        audio=context, sampling_rate=sr,
        text=[prompt], padding=True, return_tensors='pt'
    ).to(device)
    if device == 'cuda' and 'input_values' in inputs:
        inputs['input_values'] = inputs['input_values'].half()   # aligne le dtype sur le modèle fp16
    with torch.inference_mode():
        out = p3_model.generate(**inputs, max_new_tokens=max_tokens)
    return out[0, 0].float().cpu().numpy()

def p3_complete_music(audio_path: str, progress_cb=None, prompt: str = 'music') -> dict:
    if not p3_load_model():
        return {'success': False, 'path': '', 'error': 'Impossible de charger le modèle'}

    sr = p3_model.config.audio_encoder.sampling_rate
    os.makedirs('./generated', exist_ok=True)

    try:
        extract = p3_load_audio_mono(audio_path, sr)
        if extract.size == 0:                        # fichier illisible / piste vide
            return {'success': False, 'path': '', 'duration': 0,
                    'error': 'Extrait vide ou illisible (fichier audio invalide ?).'}
        # Si l'extrait dépasse déjà la cible, on le rogne : sinon le fichier de
        # sortie dépasserait les 2min30 annoncés (missing=0 ne tronque rien).
        if len(extract) > int(TARGET_DURATION * sr):
            extract = extract[:int(TARGET_DURATION * sr)]
        extract_dur = len(extract) / sr
        missing = max(0, TARGET_DURATION - extract_dur)

        intro_dur = missing * 0.45
        outro_dur = missing * 0.55
        n_intro = max(0, int(np.ceil(intro_dur / CHUNK_SIZE)))
        n_outro = max(0, int(np.ceil(outro_dur / CHUNK_SIZE)))
        total_steps = n_intro + n_outro

        if progress_cb:
            progress_cb(0, total_steps,
                f'📐 Extrait : {extract_dur:.0f}s → cible : {TARGET_DURATION}s | '
                f'intro : {intro_dur:.0f}s ({n_intro} chunks) | '
                f'outro : {outro_dur:.0f}s ({n_outro} chunks)')

        # --- INTRO ---
        # Un modèle ne génère que "vers l'avant". Pour une intro qui débouche
        # naturellement sur l'extrait, on retourne l'extrait dans le temps, on
        # le prolonge, puis on retourne le résultat (les ÉCHANTILLONS, pas juste
        # l'ordre des blocs). Le contexte reste ancré sur l'audio réel cumulé.
        if n_intro > 0:
            context = extract[::-1].copy()
            intro_chunks = []
            for i in range(n_intro):
                dur = min(CHUNK_SIZE, max(1, int(intro_dur - i * CHUNK_SIZE)))
                if progress_cb:
                    progress_cb(i + 1, total_steps, f'🎵 Intro chunk {i+1}/{n_intro} ({dur}s)...')
                chunk = p3_generate_chunk(context, sr, dur, prompt)
                intro_chunks.append(chunk)
                context = np.concatenate([context, chunk])[-(sr * 10):]   # contexte borné (seule la fin sert à generate)
            intro_audio = np.concatenate(intro_chunks)[::-1].copy()
        else:
            intro_audio = np.array([])

        # --- OUTRO ---
        if n_outro > 0:
            context = extract.copy()
            outro_chunks = []
            for i in range(n_outro):
                dur = min(CHUNK_SIZE, max(1, int(outro_dur - i * CHUNK_SIZE)))
                if progress_cb:
                    progress_cb(n_intro + i + 1, total_steps, f'🎵 Outro chunk {i+1}/{n_outro} ({dur}s)...')
                chunk = p3_generate_chunk(context, sr, dur, prompt)
                outro_chunks.append(chunk)
                context = np.concatenate([context, chunk])[-(sr * 10):]   # contexte borné (seule la fin sert à generate)
            outro_audio = np.concatenate(outro_chunks)
        else:
            outro_audio = np.array([])

        # --- CADRAGE DURÉE : borne intro/outro pour ne pas dépasser la cible ---
        # (le ceil sur le nombre de chunks peut générer un peu plus que prévu ;
        # on garde l'extrait intact et on rogne le surplus généré aux extrémités.)
        if intro_dur > 0 and len(intro_audio) > int(intro_dur * sr):
            intro_audio = intro_audio[-int(intro_dur * sr):]   # garde la fin (près de l'extrait)
        if outro_dur > 0 and len(outro_audio) > int(outro_dur * sr):
            outro_audio = outro_audio[:int(outro_dur * sr)]    # garde le début (près de l'extrait)

        # --- ÉQUILIBRAGE VOLUME : aligne intro/outro sur le pic de l'extrait réel ---
        ref_peak = float(np.max(np.abs(extract))) if extract.size else 0.0
        intro_audio = _match_peak(intro_audio, ref_peak)
        outro_audio = _match_peak(outro_audio, ref_peak)

        # --- ASSEMBLAGE (avec léger crossfade aux jonctions) ---
        full_audio = p3_crossfade_join([intro_audio, extract, outro_audio], sr, fade=0.05)
        # Nom de sortie dérivé du fichier source : évite d'écraser silencieusement
        # le résultat d'un autre morceau déjà complété.
        stem = os.path.splitext(os.path.basename(audio_path))[0]
        out_path = f'./generated/{stem}_completed.wav'
        p3_save_tmp(full_audio, sr, out_path)
        actual_dur = len(full_audio) / sr

        if progress_cb:
            progress_cb(total_steps, total_steps,
                f'✅ Assemblage terminé : {actual_dur:.0f}s ({actual_dur/60:.1f}min)')

        return {'success': True, 'path': out_path, 'duration': actual_dur, 'error': ''}

    except Exception as e:
        return {'success': False, 'path': '', 'duration': 0, 'error': str(e)}

print('✅ Fonctions Partie 3 prêtes — cible 2min30, chunks 20s, modèle small')

"""---
## 🖥️ PARTIE 4 — Interface graphique unifiée
"""

# Cellule 4.1 — Installation UI
!pip install "ipywidgets==8.1.5" --quiet
print('✅ ipywidgets installé')

# Cellule 4.2 — Interface graphique unifiée
import ipywidgets as widgets
import html as _html
from IPython.display import display, Audio, HTML, clear_output
try:
    from google.colab import files as colab_files
except ImportError:        # permet d'importer le module hors Colab (tests / lint)
    colab_files = None

import threading
# Verrou GPU/CPU : empêche l'identification (P2) et la génération (P3) de tourner
# en même temps. Deux tâches lourdes sur le même device (et sur les modèles
# globaux partagés) -> risque d'OOM ou de résultats corrompus.
_GPU_LOCK = threading.Lock()

def _run_async(button, worker, out=None):
    # Exécute le travail lourd (identification, génération) hors du thread principal
    # pour ne pas figer l'UI ; le bouton est désactivé le temps du traitement.
    def runner():
        try:
            worker()
        except Exception as e:
            # Filet : sans ça, une erreur imprévue (hors des fonctions qui catchent
            # déjà) partirait dans stderr du thread et l'UI resterait vide.
            if out is not None:
                with out:
                    display(HTML(error_card(f'Erreur inattendue : {e}')))
        finally:
            button.disabled = False
    button.disabled = True
    threading.Thread(target=runner, daemon=True).start()

# Échappement HTML : toute donnée externe (métadonnées AudD, noms de fichiers,
# messages d'erreur, labels de modèle) est passée par esc() avant injection dans
# l'UI -> évite l'injection HTML/XSS dans les cartes affichées.
def esc(value):
    return _html.escape(str(value))

def safe_url(value):
    # N'autorise que http(s) : neutralise les schémas dangereux (javascript:, data:…)
    # même quand l'URL provient d'une API externe (réponse AudD) avant injection en href.
    u = str(value or '').strip()
    return u if u.lower().startswith(('http://', 'https://')) else ''

def card(content, color='#f0fff0', border='#4CAF50'):
    return f"<div style='background:{color}; padding:14px; border-radius:10px; border:1px solid {border}; margin:6px 0;'>{content}</div>"
def error_card(msg):
    return card(f'<b>❌ Erreur</b><br>{esc(msg)}', '#fff0f0', '#f44336')
def info_card(msg):
    return card(msg, '#f0f4ff', '#5c6bc0')
def sep():
    return widgets.HTML("<hr style='border:1px solid #ddd; margin:20px 0;'>")

header = widgets.HTML("""
<div style='background:linear-gradient(135deg,#1a1a2e,#16213e,#0f3460);
     padding:24px; border-radius:14px; margin-bottom:10px;'>
  <h1 style='color:#e94560; margin:0;'>🎵 Music Studio</h1>
  <p style='color:#aaa; margin:6px 0 0 0;'>Télécharge · Identifie · Complète en 2min30</p>
</div>
""")

def refresh_dropdowns(path=''):
    choices = p1_get_audio_files() or ['Aucun fichier']
    for dd in (s2_file, s3_file):
        dd.options = choices
        if dd.value not in choices:          # évite l'exception ipywidgets
            dd.value = choices[0]
    if path and os.path.basename(path) in choices:
        s2_file.value = os.path.basename(path)
        s3_file.value = os.path.basename(path)

# Listing initial calculé une seule fois et partagé par les deux dropdowns
# (évite de globber le dossier ./downloads une fois par widget à la construction).
_initial_audio_files = p1_get_audio_files() or ['Aucun fichier']

# ── SECTION 1 ──
s1_title = widgets.HTML("<h3 style='color:#E1306C; margin-bottom:8px;'>① Télécharger un Reel / Short</h3>")
s1_hint = widgets.HTML("<span style='color:#555; font-size:13px;'>📌 Instagram Reels & YouTube Shorts / vidéos</span>")
s1_url = widgets.Text(
    placeholder='https://www.instagram.com/reel/XXX  ou  https://youtube.com/shorts/XXX',
    description='URL :',
    layout=widgets.Layout(width='620px'),
    style={'description_width': '50px'}
)
s1_fmt = widgets.ToggleButtons(
    options=[('🎵 MP3', 'mp3'), ('🔊 WAV', 'wav'), ('🎞️ MP4', 'mp4')],
    value='mp3', description='Format :',
    style={'description_width': '70px', 'button_width': '120px'}
)
s1_cookies = widgets.Text(
    placeholder='Chemin cookies.txt (optionnel — Reels privés uniquement)',
    description='Cookies :',
    layout=widgets.Layout(width='500px'),
    style={'description_width': '70px'}
)
s1_btn = widgets.Button(description='⬇️ Télécharger', button_style='danger',
    layout=widgets.Layout(width='180px', height='38px'))
s1_upload_btn = widgets.Button(description='📁 Importer depuis ordi', button_style='info',
    layout=widgets.Layout(width='210px', height='38px'))
s1_out = widgets.Output()

def on_s1_download(b):
    with s1_out:
        clear_output()
        url = s1_url.value.strip()
        if not url:
            display(HTML(error_card("Merci d'entrer une URL."))); return
        # Étiquette de source basée sur le hostname réel (et non une sous-chaîne
        # de l'URL brute, qui pouvait mal classer certaines URLs).
        from urllib.parse import urlparse
        _host = (urlparse(url).hostname or '').lower()
        src = '📸 Instagram' if (_host == 'instagram.com' or _host.endswith('.instagram.com')) else '▶️ YouTube'
        display(HTML(info_card(f'⏳ Téléchargement depuis {src}...')))
        res = p1_download(url, s1_fmt.value, s1_cookies.value.strip())
        clear_output()
        if res['success']:
            size_kb = os.path.getsize(res['path']) / 1024
            display(HTML(card(
                f"<b>✅ {src} — {esc(res['title'])}</b><br>"
                f"📁 {esc(os.path.basename(res['path']))} · {size_kb:.0f} KB"
            )))
            if s1_fmt.value in ['mp3', 'wav']:
                display(Audio(res['path']))
            if colab_files:
                colab_files.download(res['path'])
            refresh_dropdowns(res['path'])
        else:
            display(HTML(error_card(res['error'])))

def on_s1_upload(b):
    with s1_out:
        clear_output()
        if colab_files is None:
            display(HTML(error_card("Import local disponible uniquement dans Google Colab."))); return
        display(HTML(info_card('⏳ Sélectionne ton fichier...')))
        uploaded = colab_files.upload()
        if uploaded:
            os.makedirs('./downloads', exist_ok=True)
            for fname, data in uploaded.items():
                safe = os.path.basename(fname)   # neutralise un éventuel path traversal (../)
                dest = f'./downloads/{safe}'
                with open(dest, 'wb') as f:
                    f.write(data)
                display(HTML(card(f'✅ <b>{esc(safe)}</b> importé !')))
                if safe.lower().endswith(('.mp3', '.wav')):   # Audio() ne lit pas un .mp4
                    display(Audio(dest))
                refresh_dropdowns(dest)

s1_btn.on_click(on_s1_download)
s1_upload_btn.on_click(on_s1_upload)

# ── SECTION 2 ──
s2_title = widgets.HTML("<h3 style='color:#FF9800; margin-bottom:8px;'>② Identifier le titre & le style</h3>")
s2_info = widgets.HTML(info_card(
    '🎯 <b>AudD.io</b> pour le titre exact (clé gratuite sur <a href="https://dashboard.audd.io" target="_blank">dashboard.audd.io</a>) '
    '+ <b>2 modèles HuggingFace</b> pour le genre musical.<br>'
    '<span style="color:#888; font-size:12px;">Sans clé AudD, seuls les genres seront détectés. Total : ~2-4min.</span>'
))
s2_audd_key = widgets.Password(
    placeholder='Colle ta clé API AudD.io ici (optionnel)',
    description='AudD Key :',
    layout=widgets.Layout(width='500px'),
    style={'description_width': '90px'}
)
s2_file = widgets.Dropdown(
    options=_initial_audio_files,
    description='Fichier :',
    layout=widgets.Layout(width='500px'),
    style={'description_width': '70px'}
)
s2_model_select = widgets.SelectMultiple(
    options=[(m['name'], m['id']) for m in P2_MODELS],
    value=tuple(m['id'] for m in P2_MODELS),   # les 2 modèles par défaut ; décocher pour aller + vite
    description='Modèles :',
    rows=len(P2_MODELS),
    layout=widgets.Layout(width='500px'),
    style={'description_width': '70px'}
)
s2_refresh = widgets.Button(description='🔄', layout=widgets.Layout(width='50px'))
s2_refresh.on_click(lambda b: refresh_dropdowns())   # MAJ + corrige la value (évite TraitError)
s2_progress_bar = widgets.IntProgress(value=0, min=0, max=3,
    description='', layout=widgets.Layout(width='580px'))
s2_progress_label = widgets.HTML('')
s2_btn = widgets.Button(description='🔍 Identifier', button_style='warning',
    layout=widgets.Layout(width='160px', height='38px'))
s2_out = widgets.Output()

def _s2_identify_work():
    with s2_out:
        clear_output()
        fname = s2_file.value
        if fname == 'Aucun fichier':
            display(HTML(error_card("Télécharge d'abord un fichier en étape ①."))); return
        path = f'./downloads/{fname}'
        # Verrou : une seule tâche lourde (P2/P3) à la fois sur le device.
        if not _GPU_LOCK.acquire(blocking=False):
            display(HTML(info_card('⏳ Une autre tâche est déjà en cours (identification ou génération). Réessaie quand elle sera terminée.'))); return
        try:
            audd_key = s2_audd_key.value.strip()
            chosen = [m for m in P2_MODELS if m['id'] in s2_model_select.value] or P2_MODELS
            s2_progress_bar.value = 0

            def progress_cb(step, total, msg):
                s2_progress_bar.max = max(total, 1)
                s2_progress_bar.value = step
                s2_progress_label.value = info_card(msg)

            results = p2_identify_all(path, audd_key=audd_key, progress_cb=progress_cb, models=chosen)
            clear_output()

            html = "<h4 style='color:#FF9800;'>🎯 Résultats d'identification</h4>"
            tr = results['title']
            if tr['success']:
                _sp = safe_url(tr.get('spotify_url', ''))
                _ap = safe_url(tr.get('apple_url', ''))
                spotify_btn = f" &nbsp;<a href='{esc(_sp)}' target='_blank' style='color:#1DB954;'>▶ Spotify</a>" if _sp else ''
                apple_btn = f" &nbsp;<a href='{esc(_ap)}' target='_blank' style='color:#fc3c44;'>🍎 Apple Music</a>" if _ap else ''
                html += card(
                    f"<b>🎵 {esc(tr['title'])}</b> — {esc(tr['artist'])}<br>"
                    f"💿 {esc(tr['album'])} · 📅 {esc(tr.get('release_date','?'))}"
                    f"{spotify_btn}{apple_btn}",
                    '#f0fff0', '#4CAF50'
                )
            else:
                html += card(
                    f"🎵 <b>Titre non identifié</b> — {esc(tr['error'])}<br>"
                    f"<span style='color:#888; font-size:12px;'>Ajoute une clé AudD.io pour identifier le titre exact.</span>",
                    '#fff8e1', '#FFC107'
                )

            html += "<br><b style='color:#555;'>🤖 Analyse audio (genre & tags) :</b>"
            for res in results['genres']:
                if res['success']:
                    rows = ''.join([
                        f"<tr>"
                        f"<td style='padding:3px 10px;'>#{i+1}</td>"
                        f"<td style='padding:3px 10px;'><b>{esc(r['label'])}</b></td>"
                        f"<td style='padding:3px 10px; color:#4CAF50;'>{r['score']*100:.1f}%</td>"
                        f"<td style='padding:3px 10px;'><div style='background:#4CAF50; height:10px; width:{r['score']*200:.0f}px; border-radius:5px;'></div></td>"
                        f"</tr>"
                        for i, r in enumerate(res['top_results'])
                    ])
                    html += card(
                        f"<b>🤖 {res['model_name']}</b> — <span style='color:#888; font-size:12px;'>{res['description']}</span><br><br>"
                        f"<table style='border-collapse:collapse; width:100%;'>{rows}</table>",
                        '#f8f8ff', '#7c83e5'
                    )
                else:
                    html += card(
                        f"<b>🤖 {esc(res['model_name'])}</b> — ❌ {esc(res['error'])}",
                        '#fff0f0', '#f44336'
                    )
            display(HTML(html))
        finally:
            _GPU_LOCK.release()

def on_s2_identify(b):
    _run_async(s2_btn, _s2_identify_work, s2_out)

s2_btn.on_click(on_s2_identify)

# ── SECTION 3 ──
s3_title = widgets.HTML("<h3 style='color:#6200ea; margin-bottom:8px;'>③ Compléter en 2min30</h3>")
s3_info = widgets.HTML(info_card(
    '🧩 <b>Comment ça marche ?</b><br>'
    "L'extrait est conservé au centre de la piste. "
    "MusicGen génère l'intro et l'outro par chunks de <b>20s</b> enchaînés, "
    'puis tout est assemblé en un fichier WAV de <b>2min30</b>.<br>'
    '<span style="color:#888; font-size:12px;">⚠️ La génération peut prendre 5-10min selon la durée manquante.</span>'
))
s3_file = widgets.Dropdown(
    options=_initial_audio_files,
    description='Fichier :',
    layout=widgets.Layout(width='500px'),
    style={'description_width': '70px'}
)
s3_refresh = widgets.Button(description='🔄', layout=widgets.Layout(width='50px'))
s3_refresh.on_click(lambda b: refresh_dropdowns())   # MAJ + corrige la value (évite TraitError)
s3_progress_bar = widgets.IntProgress(value=0, min=0, max=100,
    description='', layout=widgets.Layout(width='580px'))
s3_progress_label = widgets.HTML('')
s3_btn = widgets.Button(description='🎼 Générer 2min30', button_style='success',
    layout=widgets.Layout(width='200px', height='42px'))
s3_out = widgets.Output()

def _s3_generate_work():
    with s3_out:
        clear_output()
        fname = s3_file.value
        if fname == 'Aucun fichier':
            display(HTML(error_card("Télécharge d'abord un fichier en étape ①."))); return
        path = f'./downloads/{fname}'
        # Verrou : une seule tâche lourde (P2/P3) à la fois sur le device.
        if not _GPU_LOCK.acquire(blocking=False):
            display(HTML(info_card('⏳ Une autre tâche est déjà en cours (identification ou génération). Réessaie quand elle sera terminée.'))); return
        try:
            s3_progress_bar.value = 0
            s3_progress_label.value = info_card('⏳ Chargement du modèle MusicGen small...')

            def progress_cb(step, total, msg):
                s3_progress_bar.max = max(total, 1)
                s3_progress_bar.value = step
                s3_progress_label.value = info_card(msg)

            res = p3_complete_music(path, progress_cb=progress_cb)
            if res['success']:
                dur = res['duration']
                size_kb = os.path.getsize(res['path']) / 1024
                display(HTML(card(
                    f"<b>✅ Musique complétée !</b><br>"
                    f"⏱️ Durée finale : <b>{dur:.0f}s ({dur/60:.1f}min)</b><br>"
                    f"📦 Taille : {size_kb:.0f} KB"
                )))
                display(Audio(res['path']))
                if colab_files:
                    colab_files.download(res['path'])
            else:
                display(HTML(error_card(res['error'])))
        finally:
            _GPU_LOCK.release()

def on_s3_generate(b):
    _run_async(s3_btn, _s3_generate_work, s3_out)

s3_btn.on_click(on_s3_generate)

# ── ASSEMBLAGE FINAL ──
ui = widgets.VBox([
    header,
    s1_title, s1_hint,
    s1_url, s1_fmt, s1_cookies,
    widgets.HBox([s1_btn, widgets.HTML('&nbsp;&nbsp;'), s1_upload_btn]),
    s1_out,
    sep(),
    s2_title, s2_info,
    s2_audd_key,
    widgets.HBox([s2_file, s2_refresh]),
    s2_model_select,
    s2_progress_bar, s2_progress_label,
    s2_btn,
    s2_out,
    sep(),
    s3_title, s3_info,
    widgets.HBox([s3_file, s3_refresh]),
    s3_progress_bar, s3_progress_label,
    s3_btn,
    s3_out,
], layout=widgets.Layout(padding='16px', width='720px'))

display(ui)